### ISSUE TITLE
Broken

### ISSUE THREAD

**Issue by Dhuls-Scratch** [FunctionalMetatable/scratch-studio-description-archiver#1]
Every time it runs, it fails with exit code 1, and this error appears:
```
0s
Run node src/index.js
internal/modules/cjs/loader.js:1089
      throw new ERR_REQUIRE_ESM(filename, parentPath, packageJsonPath);
      ^

Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /home/runner/work/scratch-studio-description-archiver/scratch-studio-description-archiver/src/node_modules/node-fetch/src/index.js
require() of ES modules is not supported.
require() of /home/runner/work/scratch-studio-description-archiver/scratch-studio-description-archiver/src/node_modules/node-fetch/src/index.js from /home/runner/work/scratch-studio-description-archiver/scratch-studio-description-archiver/src/index.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename /home/runner/work/scratch-studio-description-archiver/scratch-studio-description-archiver/src/node_modules/node-fetch/src/index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /home/runner/work/scratch-studio-description-archiver/scratch-studio-description-archiver/src/node_modules/node-fetch/package.json.

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1089:13)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/home/runner/work/scratch-studio-description-archiver/scratch-studio-description-archiver/src/index.js:3:15)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12) {
  code: 'ERR_REQUIRE_ESM'
}
Error: Process completed with exit code 1.
```

**Comment by FunctionalMetatable** [comment]
Apply these commits (https://github.com/FunctionalMetatable/scratch-studio-description-archiver/commit/61e7bfa0759f5567aafbc341e66b1b8f679d7cbd and https://github.com/FunctionalMetatable/scratch-studio-description-archiver/commit/72b7143495b37aa2f872b77015756a30fe910027) and remove package.json and package-lock.json
plus:
apply https://github.com/FunctionalMetatable/scratch-studio-description-archiver/commit/0612a5bbeb23c933dc05d735dce54812b9b3245e

**Comment by Dhuls-Scratch** [comment]
Works now. Closing.
